//==============================================================================
//
// Título:      Itaca
//
// Objetivo:    Coder en Linux aprovechando la infraestructura de tiempo real 
//		desarrollada para Resurfacing, y utilizando driver Comedi
//		
// Creado:	Mayo 2009 v1.3 A. López
//
//		Las versiones anteriores son para la DAQ NI pci6221 de 68 pines
//		Esta versión v1.3 es para la DAQ NI pci6221 de 37 pines
//		
//		Para versiones posteriors ver readme.txt
//
//		kernel 2.6.23.9 - vanilla compilado con genkernel 
//		(a partir de una instalación de gentoo)	
//
//		rtai 3.6
//		comedi 0.7.76 
//		comedilib 0.9.0
//		fltk/fluid 1.1.7
//		i686-pc-linux-gnu-g++ (GCC) 4.1.1 (Gentoo 4.1.1-r3)
//		Qt: 3.3.8
//		KDE: 3.5.8
//
// Copyright:   Fotonica Laser Systems
//
//==============================================================================

// /*

// Versiones:	
// 		v1.0 Septiembre 2008
		
// 		v1.1 Febrero 2009

// 		v1.2 Abril 2009
		
// 		v1.3 Mayo 2009
		
// 		- Adaptación a DAQ NI pci6221 37 pines
// 		- Comprobación de posición de galvos 
// 		- Comprobación de que la marca ha cabido en el campo
// 		- Velocidad constante (sin encoder)
// 		- Presentación de velocidad y tiempo marca
// 		- Control de overflow de encoder
		
// 		Para versiones posteriors ver readme.txt

// */

//==============================================================================
// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef itaca_h
#define itaca_h
#include <FL/Fl.H>
#include "includes.h" //includes del programa
#include "constantes.h" //constantes del programa
#include "variables.h" //variables globales
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *VentanaPrueba;
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern Fl_Button *Aceptar_VentanaPrueba;
extern Fl_Button *Cancelar_VentanaPrueba;
extern "C" { Fl_Double_Window* Make_Window_Confirmar_Prueba(); }
extern Fl_Double_Window *VentanaMarcar;
extern Fl_Button *Aceptar_VentanaMarcar;
extern Fl_Button *Cancelar_VentanaMarcar;
extern "C" { Fl_Double_Window* Make_Window_Confirmar_Marcar(); }
extern Fl_Double_Window *VentanaApagarSistema;
extern Fl_Button *Aceptar_VentanaApagarSistema;
extern Fl_Button *Cancelar_VentanaApagarSistema;
extern "C" { Fl_Double_Window* Make_Window_Confirmar_Apagar(); }
extern Fl_Double_Window *VentanaModificarTexto;
extern Fl_Box *LogoItacaVentanaModificar;
#include <FL/Fl_Group.H>
extern Fl_Group *GrupoFecha;
extern Fl_Button *BotonFecha;
#include <FL/Fl_Choice.H>
extern Fl_Choice *ChoiceFormatoFecha1;
extern Fl_Choice *ChoiceFormatoFecha2;
extern Fl_Choice *ChoiceFormatoFecha3;
extern Fl_Choice *ChoiceSeparadorFecha;
#include <FL/Fl_Counter.H>
extern Fl_Counter *IndicadorCaducidad;
extern Fl_Group *GrupoHora;
extern Fl_Button *BotonHora;
extern Fl_Choice *ChoiceFormatoHora1;
extern Fl_Choice *ChoiceFormatoHora2;
extern Fl_Choice *ChoiceFormatoHora3;
extern Fl_Choice *ChoiceSeparadorHora;
extern Fl_Group *GrupoSerie;
extern Fl_Button *BotonSerie;
#include <FL/Fl_Output.H>
extern Fl_Output *CuadroTextoSerie;
extern Fl_Output *CuadroTextoUnidadesLote;
extern Fl_Output *CuadroTextoSerieFinal;
extern Fl_Output *CuadroTextoUnidadesLoteActual;
extern Fl_Button *BotonReiniciarSerie;
extern Fl_Output *CuadroTextoLinea;
extern Fl_Group *GrupoTeclado;
extern Fl_Button *Boton1;
extern Fl_Button *Boton2;
extern Fl_Button *Boton3;
extern Fl_Button *Boton4;
extern Fl_Button *Boton5;
extern Fl_Button *Boton6;
extern Fl_Button *Boton7;
extern Fl_Button *Boton8;
extern Fl_Button *Boton9;
extern Fl_Button *Boton0;
extern Fl_Button *BotonBorrar;
extern Fl_Button *BotonQ;
extern Fl_Button *BotonW;
extern Fl_Button *BotonE;
extern Fl_Button *BotonR;
extern Fl_Button *BotonT;
extern Fl_Button *BotonY;
extern Fl_Button *BotonU;
extern Fl_Button *BotonI;
extern Fl_Button *BotonO;
extern Fl_Button *BotonP;
extern Fl_Button *BotonA;
extern Fl_Button *BotonS;
extern Fl_Button *BotonD;
extern Fl_Button *BotonF;
extern Fl_Button *BotonG;
extern Fl_Button *BotonH;
extern Fl_Button *BotonJ;
extern Fl_Button *BotonK;
extern Fl_Button *BotonL;
extern Fl_Button *BotonEnhe;
extern Fl_Button *BotonX;
extern Fl_Button *BotonC;
extern Fl_Button *BotonV;
extern Fl_Button *BotonB;
extern Fl_Button *BotonN;
extern Fl_Button *BotonM;
extern Fl_Button *BotonComa;
extern Fl_Button *BotonPunto;
extern Fl_Button *BotonZ;
extern Fl_Button *BotonEspacio;
extern Fl_Button *BotonBarra;
extern Fl_Button *BotonDosPuntos;
extern Fl_Button *BotonMas;
extern Fl_Button *BotonMenos;
extern Fl_Button *Cancelar_VentanaModificarTexto;
extern Fl_Button *Aceptar_VentanaModificarTexto;
extern "C" { Fl_Double_Window* Make_Window_Modificar_Texto(); }
extern "C" { void CargarVentanaModificarTexto(); }
extern Fl_Double_Window *VentanaMensaje;
extern Fl_Box *BoxVentanaMensaje;
extern Fl_Button *Aceptar_VentanaMensaje;
extern "C" { Fl_Double_Window* Make_Window_Mensaje(); }
extern "C" { void CargarTexto(); }
extern "C" { void ProcesarCaracter(const char *caracter); }
extern "C" { void ProcesarTexto(); }
extern "C" { void LineaTexto_calcular(int linea); }
extern "C" { int Leer_Configuracion(); }
extern "C" { int Leer_DAT(); }
extern "C" { int Escribir_DAT(); }
extern "C" { void Inicializar_Marcaje(); }
extern "C" { int Inicializar_DAQ_comedi(); }
extern "C" { int Desactivar_DAQ_comedi(); }
extern "C" { int Inicializar_Galvos(); }
extern "C" { int Inicializar_RTAI(); }
extern "C" { void Desactivar_RTAI(); }
extern "C" { int Inicializar_thread_estado(); }
extern "C" { void *timer_estado(void *); }
extern "C" { int Desactivar_thread_estado(); }
extern "C" { void ProcesarError(); }
extern "C" { void *timer_handler(void *args); }
extern "C" { int Inicializar_Laser(); }
extern "C" { int Desactivar_Laser(); }
extern "C" { int ControlLaser(int OnOff); }
extern "C" { int Inicializar_Encoder(); }
extern "C" { int Desactivar_Encoder(); }
extern "C" { int CalcularMatriz(); }
extern "C" { int EncontrarParametros(char caracter); }
extern "C" { int CalcularMatrizCampo(); }
extern "C" { int LeerArchivoFuentes(); }
extern "C" { void DescargarLista(int lista); }
extern "C" { int EjecutarLista(short lista); }
extern "C" { int Set_Start_List(int lista); }
extern "C" { int Set_End_Of_List(int lista); }
extern "C" { int Mark(int xdestino, int ydestino); }
extern "C" { int Jump(int xdestino, int ydestino); }
extern "C" { int PolA(int xdestino, int ydestino); }
extern "C" { int PolB(int xdestino, int ydestino); }
extern "C" { int PolC(int xdestino, int ydestino); }
extern "C" { int CalcularMarkStepSize(); }
extern "C" { int CalcularJumpStepSize(); }
extern "C" { int StopEjecucion(); }
extern "C" { int ControlEjecucionListas(); }
extern "C" { int ControlMarkInProgress(int OnOff); }
extern "C" { int EjecutarMicrovector(int lista); }
extern "C" { int ActualizarFechaHoraSerie(); }
extern "C" { int Mayusculas(char caracter); }
extern "C" { int CalcularMoverGalvos(int xdestino, int ydestino); }
extern "C" { void MoverGalvos(); }
extern "C" { int ObtenerPosicionActual(); }
extern "C" { int ComprobarPosicion(int x_teorica, int y_teorica); }
void InicializarIndicadorHorizontal();
void InicializarIndicadorVertical();
lsampl_t itaca_comedi_from_phys(double volts);
double itaca_comedi_to_phys(lsampl_t dato);
lsampl_t itaca_comedi_reset(comedi_t *device, unsigned subdevice);
lsampl_t itaca_comedi_arm(comedi_t *device, unsigned subdevice, unsigned target);
lsampl_t itaca_comedi_set_counter_mode(comedi_t *device, unsigned subdevice, unsigned channel, unsigned mode_bits);
lsampl_t itaca_comedi_set_clock_source(comedi_t *device, unsigned subdevice, unsigned clock, unsigned period_ns);
lsampl_t itaca_comedi_set_gate_source(comedi_t *device, unsigned subdevice, unsigned channel,
	unsigned gate_index, unsigned gate_source);
lsampl_t itaca_comedi_set_routing(comedi_t *device, unsigned subdevice, unsigned channel, unsigned routing);
extern "C" { void ActualizaUI(void *); }
extern Fl_Double_Window *VentanaPrincipal;
extern Fl_Box *LedLaser;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *CuadroTextoContador;
extern Fl_Value_Output *CuadroTextoVLinea;
extern Fl_Value_Output *CuadroTextoTMarca;
extern Fl_Button *LedEstado;
extern Fl_Box *LogoItacaVentanaPrincipal;
extern Fl_Group *GrupoControlIntensidad;
extern Fl_Counter *IndicadorPotencia;
extern Fl_Counter *IndicadorVelocidad;
extern Fl_Group *GrupoControlMarca;
extern Fl_Counter *IndicadorHorizontal;
extern Fl_Counter *IndicadorVertical;
extern Fl_Choice *ChoiceFuente;
extern Fl_Counter *IndicadorAnchura;
extern Fl_Counter *IndicadorEspaciado;
extern Fl_Counter *IndicadorSeparacion;
extern Fl_Group *SubgrupoJustificacion;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *CheckJustificacionCentro;
extern Fl_Round_Button *CheckJustificacionDerecha;
extern Fl_Round_Button *CheckJustificacionIzquierda;
extern Fl_Group *GrupoControlTexto;
extern Fl_Group *SubGrupoLinea1;
extern Fl_Output *CuadroTextoLinea1;
extern Fl_Counter *IndicadorAlturaLinea1;
extern Fl_Group *SubGrupoLinea2;
extern Fl_Output *CuadroTextoLinea2;
extern Fl_Counter *IndicadorAlturaLinea2;
extern Fl_Group *SubGrupoLinea3;
extern Fl_Output *CuadroTextoLinea3;
extern Fl_Counter *IndicadorAlturaLinea3;
extern Fl_Group *GrupoControlOperacion;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *BotonMarcar;
extern Fl_Light_Button *BotonPrueba;
extern Fl_Button *BotonStop;
extern Fl_Button *BotonApagar;
extern Fl_Light_Button *BotonLaser;
extern Fl_Light_Button *BotonCampo;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *CheckCentrado;
#endif
