// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef itaca_config_h
#define itaca_config_h
#include <FL/Fl.H>
#include "config.h" //variables globales
extern "C" { int leer_configuracion(); }
extern "C" { int escribir_configuracion(); }
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *VentanaConfiguracion;
#include <FL/Fl_Box.H>
extern Fl_Box *EtiquetaLinea;
extern Fl_Box *EtiquetaDisparo;
extern Fl_Box *EtiquetaAvanzado;
extern Fl_Box *EtiquetaSistema;
#include <FL/Fl_Counter.H>
extern Fl_Counter *CounterPeriodo;
extern Fl_Counter *CounterRetardoLaserOn;
extern Fl_Counter *CounterRetardoLaserOff;
extern Fl_Counter *CounterCalibracion;
extern Fl_Counter *CounterVelocidadSalto;
extern Fl_Counter *CounterRetardoSalto;
extern Fl_Counter *CounterRetardoPoligono;
extern Fl_Counter *CounterRetardoMarcaje;
extern Fl_Counter *CounterControlGalvos;
#include <FL/Fl_Choice.H>
extern Fl_Choice *ChoiceValorActivacionGalvos;
extern Fl_Choice *ChoiceOrientacion;
extern Fl_Choice *ChoiceAvance;
extern Fl_Choice *ChoiceDisparoFotocelula;
extern Fl_Counter *CounterRetardoDisparo;
extern Fl_Counter *CounterLecturasConsecutivas;
extern Fl_Counter *CounterSeparacionEntreDisparos;
extern Fl_Choice *ChoiceTipoDisparo;
extern Fl_Choice *ChoiceMarcajeDinamico;
extern Fl_Counter *CounterEncoder;
extern Fl_Counter *CounterVelocidadLinea;
extern Fl_Choice *ChoiceIdioma;
#include <FL/Fl_Button.H>
extern Fl_Button *BotonCambiarFechaHora;
extern Fl_Counter *CounterPeriodoRT;
extern Fl_Choice *ChoiceExtractor;
extern Fl_Choice *ChoiceServicioTecnico;
extern Fl_Counter *CounterSpot;
extern Fl_Button *BotonImportarGraficos;
extern Fl_Choice *ChoiceControlPuertoSerie;
extern Fl_Choice *ChoiceCentrado;
extern Fl_Button *BotonAceptar;
extern Fl_Button *BotonCancelar;
extern Fl_Choice *ChoiceReverso;
extern Fl_Choice *ChoiceControlEstrategia;
extern Fl_Choice *ChoiceControl;
extern Fl_Choice *ChoiceErrorCampo;
extern Fl_Choice *ChoiceErrorGalvos;
extern Fl_Button *BotonTurnos;
extern Fl_Choice *ChoiceTipoLaser;
extern Fl_Choice *ChoiceFicheroCorreccionActivo;
Fl_Double_Window* Make_Window();
extern Fl_Double_Window *VentanaPassword;
#include <FL/Fl_Output.H>
extern Fl_Output *CuadroTextoPassword;
#include <FL/Fl_Group.H>
extern Fl_Group *GrupoTeclado;
extern Fl_Button *Boton1p;
extern Fl_Button *Boton2p;
extern Fl_Button *Boton3p;
extern Fl_Button *Boton4p;
extern Fl_Button *Boton5p;
extern Fl_Button *Boton6p;
extern Fl_Button *Boton7p;
extern Fl_Button *Boton8p;
extern Fl_Button *Boton9p;
extern Fl_Button *Boton0p;
extern Fl_Button *BotonBorrarp;
extern Fl_Button *Cancelar_VentanaPassword;
extern Fl_Button *Aceptar_VentanaPassword;
extern "C" { Fl_Double_Window* Make_Window_Password(); }
extern Fl_Double_Window *VentanaMensaje;
extern Fl_Box *BoxVentanaMensaje;
extern Fl_Button *Aceptar_VentanaMensaje;
extern "C" { Fl_Double_Window* Make_Window_Mensaje(); }
extern Fl_Double_Window *VentanaTurnos;
extern Fl_Box *LogoItacaVentanaTrabajos;
extern Fl_Output *CuadroTextoTurno0;
extern Fl_Group *GrupoTecladoTrabajos;
extern Fl_Button *Boton1t;
extern Fl_Button *Boton2t;
extern Fl_Button *Boton3t;
extern Fl_Button *Boton4t;
extern Fl_Button *Boton5t;
extern Fl_Button *Boton6t;
extern Fl_Button *Boton7t;
extern Fl_Button *Boton8t;
extern Fl_Button *Boton9t;
extern Fl_Button *Boton0t;
extern Fl_Button *BotonBorrart;
extern Fl_Button *BotonQt;
extern Fl_Button *BotonWt;
extern Fl_Button *BotonEt;
extern Fl_Button *BotonRt;
extern Fl_Button *BotonTt;
extern Fl_Button *BotonYt;
extern Fl_Button *BotonUt;
extern Fl_Button *BotonIt;
extern Fl_Button *BotonOt;
extern Fl_Button *BotonPt;
extern Fl_Button *BotonAt;
extern Fl_Button *BotonSt;
extern Fl_Button *BotonDt;
extern Fl_Button *BotonFt;
extern Fl_Button *BotonGt;
extern Fl_Button *BotonHt;
extern Fl_Button *BotonJt;
extern Fl_Button *BotonKt;
extern Fl_Button *BotonLt;
extern Fl_Button *BotonEnhet;
extern Fl_Button *BotonXt;
extern Fl_Button *BotonCt;
extern Fl_Button *BotonVt;
extern Fl_Button *BotonBt;
extern Fl_Button *BotonNt;
extern Fl_Button *BotonMt;
extern Fl_Button *BotonZt;
extern Fl_Button *BotonEspaciot;
extern Fl_Button *BotonMenost;
extern Fl_Button *Aceptar_VentanaTurnos;
extern Fl_Button *Cancelar_VentanaTurnos;
extern Fl_Counter *CounterHoraInicioTurno0;
extern Fl_Counter *CounterMinutoInicioTurno0;
extern Fl_Counter *CounterHoraFinTurno0;
extern Fl_Counter *CounterMinutoFinTurno0;
extern Fl_Output *CuadroTextoTurno1;
extern Fl_Counter *CounterHoraInicioTurno1;
extern Fl_Counter *CounterMinutoInicioTurno1;
extern Fl_Counter *CounterHoraFinTurno1;
extern Fl_Counter *CounterMinutoFinTurno1;
extern Fl_Output *CuadroTextoTurno2;
extern Fl_Counter *CounterHoraInicioTurno2;
extern Fl_Counter *CounterMinutoInicioTurno2;
extern Fl_Counter *CounterHoraFinTurno2;
extern Fl_Counter *CounterMinutoFinTurno2;
extern Fl_Output *CuadroTextoTurno3;
extern Fl_Counter *CounterHoraInicioTurno3;
extern Fl_Counter *CounterMinutoInicioTurno3;
extern Fl_Counter *CounterHoraFinTurno3;
extern Fl_Counter *CounterMinutoFinTurno3;
extern Fl_Output *CuadroTextoTurno4;
extern Fl_Counter *CounterHoraInicioTurno4;
extern Fl_Counter *CounterMinutoInicioTurno4;
extern Fl_Counter *CounterHoraFinTurno4;
extern Fl_Counter *CounterMinutoFinTurno4;
extern Fl_Output *CuadroTextoTurno5;
extern Fl_Counter *CounterHoraInicioTurno5;
extern Fl_Counter *CounterMinutoInicioTurno5;
extern Fl_Counter *CounterHoraFinTurno5;
extern Fl_Counter *CounterMinutoFinTurno5;
extern Fl_Box *b1;
extern Fl_Box *b2;
extern Fl_Box *b3;
extern Fl_Box *b4;
extern Fl_Box *b5;
extern Fl_Box *b6;
extern "C" { Fl_Double_Window* Make_Window_Turnos(); }
extern "C" { void CargarVentanaTurnos(); }
#endif
